#!/bin/bash
#============================================================================
# Title       : install_pgio
# Description : Installer for pypgio
# Author      : Bart Sjerps <bart@dirty-cache.com>
# License     : GPLv3+
# ---------------------------------------------------------------------------

# This file can safely be removed after installation

# Create ~/bin directory if needed
test -d ~/bin || mkdir ~/bin

# Create and activate venv
python3 -m venv ~/pgio_venv
source ~/pgio_venv/bin/activate

# Update PIP
pip install --upgrade pip

# Install and list required packages
pip install psycopg psycopg-binary prettytable
pip list

# Add bash profile entries
grep -q pgio ~/.bashrc || cat <<- EOF >> ~/.bashrc
	
	# bash completion for pgio
	source \$HOME/bin/complete_pgio
	
	# Virtual ENV for pgio
	export PATH=\$HOME/pgio_venv/bin:\$PATH
	
	EOF
