#!/bin/bash
#============================================================================
# Title       : complete_pgio
# Description : bash_completion file for pypgio
# Author      : Bart Sjerps <bart@dirty-cache.com>
# License     : GPLv3+
# ---------------------------------------------------------------------------
# This file must be used with "source complete_pgio" *from bash*
# you cannot run it directly
# ---------------------------------------------------------------------------
    
_pypgio() {
  local cur prev opts cmd configure
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  cmd="${COMP_WORDS[1]}"
  opts="destroy configure setup list run report abort complete"
  configure="--defaults --dbhost --dbname --dbuser --dbpass --dbport --update_pct --scale --schemas --work_unit --update_unit --tablespace"
  if (( $COMP_CWORD == 1 )); then
    COMPREPLY=($(compgen -W "-h --version --tabs -nohead --debug $opts" -- ${cur}))
  fi
  if (( $COMP_CWORD > 1 )); then
    prev2="${COMP_WORDS[COMP_CWORD-2]}"
    case "$prev" in
      --tabs|-t|--nohead|-n|--debug|-D) COMPREPLY=($(compgen -W "-h --version --tabs -nohead --debug $opts" -- ${cur}));;
      configure) COMPREPLY=($(compgen -W "${configure}" -- ${cur})) ;;
    esac
    case "$cmd$prev2" in
      configure--*) COMPREPLY=($(compgen -W "${configure}" -- ${cur})) ;;
    esac
  fi
}

complete -o nosort -F _pypgio pypgio

# Permanent:
# pypgio complete > $HOME/.local/share/bash-completion/completions
# Activate completions (on bash shell):
# source <(pypgio complete)

