#!/bin/bash
#============================================================================
# Title       : pgio
# Description : wrapper for pypgio
# Author      : Bart Sjerps <bart@dirty-cache.com>
# License     : GPLv3+
# ---------------------------------------------------------------------------
# Calls pypgio from the Python virtual environment
# This eliminates the need for the user to activate the environment first
# ---------------------------------------------------------------------------

venv=$HOME/.virtualenvs/pgio_venv

usage() {
    echo "$0"
  cat <<- EOF
	No virtual environment on $venv
    $0
	
	Run python3 $0/install first
	
	EOF
}

test -d $venv || { usage ; exit 10 ; }

source $venv/bin/activate
pypgio "$@"
